export default {
  MINIMUM_PC_WIDTH: 1280,
  SIDEMENU_WIDTH: 300,
  SIDEMENU_PAPER_WIDTH: 280,
  MAIN_GRIDTILE_WIDTH: 250,
  MAIN_GRIDTILE_HEIGHT: 180,
  MAIN_GRIDLIST_PAD: 12,
};
export const getWinSize = () => window.innerWidth;
